# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ''
tagline:             ''
description:         ''
url:                 ''
baseurl:             'https://shelleycavaness.github.io/deviations'
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             someone@gmail.com

# Custom vars
version:             1.0.0
